# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class DnsSettings(Model):
    """DNS Proxy Settings in Firewall Policy.

    :param servers: List of Custom DNS Servers.
    :type servers: list[str]
    :param enable_proxy: Enable DNS Proxy on Firewalls attached to the
     Firewall Policy.
    :type enable_proxy: bool
    :param require_proxy_for_network_rules: FQDNs in Network Rules are
     supported when set to true.
    :type require_proxy_for_network_rules: bool
    """

    _attribute_map = {
        'servers': {'key': 'servers', 'type': '[str]'},
        'enable_proxy': {'key': 'enableProxy', 'type': 'bool'},
        'require_proxy_for_network_rules': {'key': 'requireProxyForNetworkRules', 'type': 'bool'},
    }

    def __init__(self, **kwargs):
        super(DnsSettings, self).__init__(**kwargs)
        self.servers = kwargs.get('servers', None)
        self.enable_proxy = kwargs.get('enable_proxy', None)
        self.require_proxy_for_network_rules = kwargs.get('require_proxy_for_network_rules', None)
