# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class FirewallPolicyThreatIntelWhitelist(Model):
    """ThreatIntel Whitelist for Firewall Policy.

    :param ip_addresses: List of IP addresses for the ThreatIntel Whitelist.
    :type ip_addresses: list[str]
    :param fqdns: List of FQDNs for the ThreatIntel Whitelist.
    :type fqdns: list[str]
    """

    _attribute_map = {
        'ip_addresses': {'key': 'ipAddresses', 'type': '[str]'},
        'fqdns': {'key': 'fqdns', 'type': '[str]'},
    }

    def __init__(self, **kwargs):
        super(FirewallPolicyThreatIntelWhitelist, self).__init__(**kwargs)
        self.ip_addresses = kwargs.get('ip_addresses', None)
        self.fqdns = kwargs.get('fqdns', None)
