# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class FirewallPolicyRuleCollection(Model):
    """Properties of the rule collection.

    You probably want to use the sub-classes and not this class directly. Known
    sub-classes are: FirewallPolicyNatRuleCollection,
    FirewallPolicyFilterRuleCollection

    All required parameters must be populated in order to send to Azure.

    :param name: The name of the rule collection.
    :type name: str
    :param priority: Priority of the Firewall Policy Rule Collection resource.
    :type priority: int
    :param rule_collection_type: Required. Constant filled by server.
    :type rule_collection_type: str
    """

    _validation = {
        'priority': {'maximum': 65000, 'minimum': 100},
        'rule_collection_type': {'required': True},
    }

    _attribute_map = {
        'name': {'key': 'name', 'type': 'str'},
        'priority': {'key': 'priority', 'type': 'int'},
        'rule_collection_type': {'key': 'ruleCollectionType', 'type': 'str'},
    }

    _subtype_map = {
        'rule_collection_type': {'FirewallPolicyNatRuleCollection': 'FirewallPolicyNatRuleCollection', 'FirewallPolicyFilterRuleCollection': 'FirewallPolicyFilterRuleCollection'}
    }

    def __init__(self, **kwargs):
        super(FirewallPolicyRuleCollection, self).__init__(**kwargs)
        self.name = kwargs.get('name', None)
        self.priority = kwargs.get('priority', None)
        self.rule_collection_type = None
