# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from .firewall_policy_rule_collection import FirewallPolicyRuleCollection


class FirewallPolicyNatRuleCollection(FirewallPolicyRuleCollection):
    """Firewall Policy NAT Rule Collection.

    All required parameters must be populated in order to send to Azure.

    :param name: The name of the rule collection.
    :type name: str
    :param priority: Priority of the Firewall Policy Rule Collection resource.
    :type priority: int
    :param rule_collection_type: Required. Constant filled by server.
    :type rule_collection_type: str
    :param action: The action type of a Nat rule collection.
    :type action: ~firewallpolicy.models.FirewallPolicyNatRuleCollectionAction
    :param rules: List of rules included in a rule collection.
    :type rules: list[~firewallpolicy.models.FirewallPolicyRule]
    """

    _validation = {
        'priority': {'maximum': 65000, 'minimum': 100},
        'rule_collection_type': {'required': True},
    }

    _attribute_map = {
        'name': {'key': 'name', 'type': 'str'},
        'priority': {'key': 'priority', 'type': 'int'},
        'rule_collection_type': {'key': 'ruleCollectionType', 'type': 'str'},
        'action': {'key': 'action', 'type': 'FirewallPolicyNatRuleCollectionAction'},
        'rules': {'key': 'rules', 'type': '[FirewallPolicyRule]'},
    }

    def __init__(self, **kwargs):
        super(FirewallPolicyNatRuleCollection, self).__init__(**kwargs)
        self.action = kwargs.get('action', None)
        self.rules = kwargs.get('rules', None)
        self.rule_collection_type = 'FirewallPolicyNatRuleCollection'
