# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from enum import Enum


class ProvisioningState(str, Enum):

    succeeded = "Succeeded"
    updating = "Updating"
    deleting = "Deleting"
    failed = "Failed"


class AzureFirewallThreatIntelMode(str, Enum):

    alert = "Alert"
    deny = "Deny"
    off = "Off"


class FirewallPolicyNatRuleCollectionActionType(str, Enum):

    dnat = "DNAT"


class FirewallPolicyFilterRuleCollectionActionType(str, Enum):

    allow = "Allow"
    deny = "Deny"


class FirewallPolicyRuleApplicationProtocolType(str, Enum):

    http = "Http"
    https = "Https"


class FirewallPolicyRuleNetworkProtocol(str, Enum):

    tcp = "TCP"
    udp = "UDP"
    any = "Any"
    icmp = "ICMP"
