# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.0.6349, generator: {generator})
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from enum import Enum
from six import with_metaclass
from azure.core import CaseInsensitiveEnumMeta


class AzureFirewallApplicationRuleProtocolType(with_metaclass(CaseInsensitiveEnumMeta, str, Enum)):
    """The protocol type of a Application Rule resource.
    """

    HTTP = "Http"
    HTTPS = "Https"
    MSSQL = "Mssql"

class AzureFirewallNatRCActionType(with_metaclass(CaseInsensitiveEnumMeta, str, Enum)):
    """The action type of a NAT rule collection.
    """

    SNAT = "Snat"
    DNAT = "Dnat"

class AzureFirewallNetworkRuleProtocol(with_metaclass(CaseInsensitiveEnumMeta, str, Enum)):
    """The protocol of a Network Rule resource.
    """

    TCP = "TCP"
    UDP = "UDP"
    ANY = "Any"
    ICMP = "ICMP"

class AzureFirewallRCActionType(with_metaclass(CaseInsensitiveEnumMeta, str, Enum)):
    """The action type of a rule collection.
    """

    ALLOW = "Allow"
    DENY = "Deny"

class AzureFirewallSkuName(with_metaclass(CaseInsensitiveEnumMeta, str, Enum)):
    """Name of an Azure Firewall SKU.
    """

    AZFW_VNET = "AZFW_VNet"
    AZFW_HUB = "AZFW_Hub"

class AzureFirewallSkuTier(with_metaclass(CaseInsensitiveEnumMeta, str, Enum)):
    """Tier of an Azure Firewall.
    """

    STANDARD = "Standard"
    PREMIUM = "Premium"
    BASIC = "Basic"

class AzureFirewallThreatIntelMode(with_metaclass(CaseInsensitiveEnumMeta, str, Enum)):
    """The operation mode for Threat Intel.
    """

    ALERT = "Alert"
    DENY = "Deny"
    OFF = "Off"

class ProvisioningState(with_metaclass(CaseInsensitiveEnumMeta, str, Enum)):
    """The current provisioning state.
    """

    SUCCEEDED = "Succeeded"
    UPDATING = "Updating"
    DELETING = "Deleting"
    FAILED = "Failed"
