# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class AzureFirewallSku(Model):
    """SKU of an Azure Firewall.

    :param name: Name of an Azure Firewall SKU. Possible values include:
     'AZFW_VNet', 'AZFW_Hub'
    :type name: str or ~azurefirewall.models.AzureFirewallSkuName
    :param tier: Tier of an Azure Firewall. Possible values include:
     'Standard', 'Premium'
    :type tier: str or ~azurefirewall.models.AzureFirewallSkuTier
    """

    _attribute_map = {
        'name': {'key': 'name', 'type': 'str'},
        'tier': {'key': 'tier', 'type': 'str'},
    }

    def __init__(self, *, name=None, tier=None, **kwargs) -> None:
        super(AzureFirewallSku, self).__init__(**kwargs)
        self.name = name
        self.tier = tier
