# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class HubPublicIPAddresses(Model):
    """Public IP addresses associated with azure firewall.

    :param addresses: The list of Public IP addresses associated with azure
     firewall or IP addresses to be retained.
    :type addresses: list[~azurefirewall.models.AzureFirewallPublicIPAddress]
    :param count: The number of Public IP addresses associated with azure
     firewall.
    :type count: int
    """

    _attribute_map = {
        'addresses': {'key': 'addresses', 'type': '[AzureFirewallPublicIPAddress]'},
        'count': {'key': 'count', 'type': 'int'},
    }

    def __init__(self, **kwargs):
        super(HubPublicIPAddresses, self).__init__(**kwargs)
        self.addresses = kwargs.get('addresses', None)
        self.count = kwargs.get('count', None)
