# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class HubIPAddresses(Model):
    """IP addresses associated with azure firewall.

    :param public_ips: Public IP addresses associated with azure firewall.
    :type public_ips: ~azurefirewall.models.HubPublicIPAddresses
    :param private_ip_address: Private IP Address associated with azure
     firewall.
    :type private_ip_address: str
    """

    _attribute_map = {
        'public_ips': {'key': 'publicIPs', 'type': 'HubPublicIPAddresses'},
        'private_ip_address': {'key': 'privateIPAddress', 'type': 'str'},
    }

    def __init__(self, *, public_ips=None, private_ip_address: str=None, **kwargs) -> None:
        super(HubIPAddresses, self).__init__(**kwargs)
        self.public_ips = public_ips
        self.private_ip_address = private_ip_address
